spring:
  application:
    name: FILE_MANAGEMENT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file_management
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true